package org.twightlight.skywarstrainer.combat.counter;

import javax.annotation.Nonnull;

/**
 * Data class holding modifiers to apply when fighting a specific enemy.
 * Generated by {@link CounterStrategySelector} based on the enemy's
 * {@link EnemyProfile}.
 *
 * <p>These modifiers adjust the bot's combat and decision-making behavior
 * to counter the observed enemy style. They are consumed by CombatEngine,
 * EngagementPatternManager, and ApproachEngine.</p>
 */
public class CounterModifiers {

    /** Preferred engagement distance for this enemy. */
    public double preferredRange = 3.0;

    /** Whether to increase strafing to dodge projectiles. */
    public boolean dodgeProjectiles = false;

    /** Whether to actively avoid void edges when fighting this enemy. */
    public boolean avoidVoidEdge = false;

    /** Whether to use projectiles before closing to melee. */
    public boolean useProjectilesFirst = false;

    /** Whether to play passively (trade hits only, don't commit). */
    public boolean playPassive = false;

    /** Whether to prioritize cutting this enemy's bridges. */
    public boolean bridgeCut = false;

    /** Whether to be suspicious of bait/trap plays from this enemy. */
    public boolean watchForBait = false;

    /** Multiplier for FIGHT utility against this enemy (1.0 = normal). */
    public double fightUtilityMultiplier = 1.0;

    /** Multiplier for FLEE utility when this enemy is the primary threat. */
    public double fleeUtilityMultiplier = 1.0;

    /** Multiplier for CAMP utility when this enemy is nearby. */
    public double campUtilityMultiplier = 1.0;

    /**
     * Creates default (neutral) counter modifiers.
     */
    public CounterModifiers() {
        // All defaults are already set above
    }

    /**
     * Returns a description of the active counter modifiers for debug output.
     *
     * @return a human-readable description
     */
    @Nonnull
    public String describe() {
        StringBuilder sb = new StringBuilder("CounterMods{");
        if (dodgeProjectiles) sb.append("dodge,");
        if (avoidVoidEdge) sb.append("avoidVoid,");
        if (useProjectilesFirst) sb.append("ranged,");
        if (playPassive) sb.append("passive,");
        if (bridgeCut) sb.append("bridgeCut,");
        if (watchForBait) sb.append("watchBait,");
        sb.append(String.format("range=%.1f", preferredRange));
        sb.append("}");
        return sb.toString();
    }
}
