package org.twightlight.skywarstrainer.ai.strategy;

import org.twightlight.skywarstrainer.SkyWarsTrainer;
import org.twightlight.skywarstrainer.ai.decision.DecisionContext;
import org.twightlight.skywarstrainer.ai.decision.DecisionEngine.BotAction;
import org.twightlight.skywarstrainer.ai.learning.LearningEngine;
import org.twightlight.skywarstrainer.ai.llm.LLMManager;
import org.twightlight.skywarstrainer.awareness.GamePhaseTracker;
import org.twightlight.skywarstrainer.bot.TrainerBot;
import org.twightlight.skywarstrainer.config.DifficultyConfig.DifficultyProfile;
import org.twightlight.skywarstrainer.util.DebugLogger;
import org.twightlight.skywarstrainer.util.MathUtil;
import org.twightlight.skywarstrainer.util.RandomUtil;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

/**
 * The Strategy Planning System — operates on a longer time horizon than the DecisionEngine.
 *
 * <p>While the DecisionEngine evaluates "what should I do RIGHT NOW" every ~10 ticks,
 * the StrategyPlanner formulates a multi-step game plan spanning 30-120 seconds.
 * The plan biases the DecisionEngine's utility scores via action multipliers.</p>
 *
 * <p>Plans are generated by selecting from a library of META PRESETS, then blending
 * the preset with real-time contextual calculations (equipment score, health,
 * player count, personality, learning data, and optionally LLM advice).</p>
 *
 * <p><strong>Meta Presets</strong> are based on real competitive SkyWars strategies:</p>
 * <ul>
 *   <li><strong>SPEED_RUSH</strong> — Rush mid immediately for superior gear, then hunt</li>
 *   <li><strong>ISLAND_LOOT_THEN_FIGHT</strong> — Full loot own island, enchant, then engage</li>
 *   <li><strong>DEFENSIVE_FORT</strong> — Fortify position, camp, counter-punch incoming rushers</li>
 *   <li><strong>ISLAND_ROTATION</strong> — Rotate through empty islands for maximum gear before engaging</li>
 *   <li><strong>THIRD_PARTY</strong> — Wait for others to fight, clean up the survivors</li>
 *   <li><strong>EARLY_AGGRO</strong> — Rush nearest player's island with minimal gear</li>
 *   <li><strong>ENCHANT_STACK</strong> — Rush mid for enchanting table, max out gear, then dominate</li>
 * </ul>
 */
public class StrategyPlanner {

    /** Confidence threshold below which the plan is discarded and re-generated. */
    private static final double CONFIDENCE_THRESHOLD = 0.15;

    private final TrainerBot bot;

    /** The currently active strategy plan. May be null if planning is disabled. */
    private StrategyPlan activePlan;

    /** LLM-sourced multipliers that persist until the next LLM update. */
    private Map<BotAction, Double> llmMultipliers;

    /** Confidence of the last LLM advice, used for blending in getActiveMultipliers(). */
    private double lastLLMConfidence;

    /** Description from last LLM advice for debug output. */
    private String lastLLMAdvice;

    /** Tracks how many ticks since the last LLM consult request. */
    private int ticksSinceLastLLMConsult;

    /**
     * Creates a new StrategyPlanner for the given bot.
     *
     * @param bot the owning trainer bot
     */
    public StrategyPlanner(@Nonnull TrainerBot bot) {
        this.bot = bot;
        this.activePlan = null;
        this.llmMultipliers = new EnumMap<>(BotAction.class);
        this.lastLLMAdvice = null;
        this.lastLLMConfidence = 0.0;
        this.ticksSinceLastLLMConsult = 0;
    }

    // ═════════════════════════════════════════════════════════════
    //  META PRESET DEFINITIONS
    // ═════════════════════════════════════════════════════════════

    /**
     * All recognized meta strategy presets. Each preset defines a multi-phase
     * template that gets blended with real-time context for the final plan.
     */
    public enum MetaPreset {
        SPEED_RUSH,
        ISLAND_LOOT_THEN_FIGHT,
        DEFENSIVE_FORT,
        ISLAND_ROTATION,
        THIRD_PARTY,
        EARLY_AGGRO,
        ENCHANT_STACK
    }

    // ─── Tick ───────────────────────────────────────────────────

    /**
     * Called periodically from the TrainerBot tick loop (every ~100 ticks).
     * Checks plan validity, generates a new plan if needed, and optionally
     * triggers an LLM consult for higher-difficulty bots.
     */
    public void tick() {
        DifficultyProfile diff = bot.getDifficultyProfile();
        if (diff == null || !diff.isStrategyPlanningEnabled()) {
            activePlan = null;
            return;
        }

        DecisionContext context = null;
        if (bot.getDecisionEngine() != null) {
            context = bot.getDecisionEngine().getContext();
        }
        if (context == null) return;

        // Update existing plan
        if (activePlan != null) {
            boolean stillValid = activePlan.update(context, diff.getPlanConfidenceDecayRate());
            if (!stillValid || activePlan.getConfidence() < CONFIDENCE_THRESHOLD) {
                DebugLogger.log(bot, "Strategy plan expired (conf=%.2f, completed=%s). Re-planning.",
                        activePlan.getConfidence(), activePlan.isCompleted());
                activePlan = null;
            }
        }

        // Generate new plan if needed
        if (activePlan == null) {
            activePlan = generatePlan(context);
            if (activePlan != null) {
                DebugLogger.log(bot, "New strategy plan: %s", activePlan.getPlanDescription());
            }
        }

        // ── [FIX] LLM Consult — actually request advice on interval ──
        ticksSinceLastLLMConsult++;
        double llmConsultChance = diff.getPlanLLMConsultChance();
        if (llmConsultChance > 0.0 && ticksSinceLastLLMConsult >= 200) {
            if (RandomUtil.chance(llmConsultChance)) {
                requestLLMAdvice();
                ticksSinceLastLLMConsult = 0;
            }
        }
    }

    // ─── LLM Consult ────────────────────────────────────────────

    /**
     * Requests strategic advice from the LLM system if available.
     * This is called from the tick loop based on planLLMConsultChance.
     */
    private void requestLLMAdvice() {
        SkyWarsTrainer plugin = bot.getPlugin();
        if (plugin == null) return;

        LLMManager llmManager = plugin.getLLMManager();
        if (llmManager == null || !llmManager.isAvailable()) return;

        llmManager.requestStrategicAdvice(bot);
        DebugLogger.log(bot, "StrategyPlanner: Triggered LLM consult request.");
    }

    // ─── Plan Generation ────────────────────────────────────────

    /**
     * Generates a multi-phase strategy plan by selecting the best meta preset
     * for the current situation, then blending it with contextual calculations.
     *
     * @param context the current decision context
     * @return a new StrategyPlan, or null if planning fails
     */
    @Nullable
    public StrategyPlan generatePlan(@Nonnull DecisionContext context) {
        DifficultyProfile diff = bot.getDifficultyProfile();
        int maxPhases = diff.getPlanComplexity();
        boolean hasFallbacks = diff.isPlanFallbackEnabled();

        // Step 1: Select the best meta preset
        MetaPreset preset = selectPreset(context, diff);

        // Step 2: Get learned preferences
        Map<BotAction, Double> learnedPreferences = getLearnedPreferences(context, diff);

        // Step 3: Generate phases from preset + context blend
        List<StrategicPhase> phases = new ArrayList<>();
        StringBuilder description = new StringBuilder();
        description.append("[").append(preset.name()).append("] ");

        switch (preset) {
            case SPEED_RUSH:
                generateSpeedRushPhases(phases, description, context, diff, maxPhases, hasFallbacks, learnedPreferences);
                break;
            case ISLAND_LOOT_THEN_FIGHT:
                generateIslandLootThenFightPhases(phases, description, context, diff, maxPhases, hasFallbacks, learnedPreferences);
                break;
            case DEFENSIVE_FORT:
                generateDefensiveFortPhases(phases, description, context, diff, maxPhases, hasFallbacks, learnedPreferences);
                break;
            case ISLAND_ROTATION:
                generateIslandRotationPhases(phases, description, context, diff, maxPhases, hasFallbacks, learnedPreferences);
                break;
            case THIRD_PARTY:
                generateThirdPartyPhases(phases, description, context, diff, maxPhases, hasFallbacks, learnedPreferences);
                break;
            case EARLY_AGGRO:
                generateEarlyAggroPhases(phases, description, context, diff, maxPhases, hasFallbacks, learnedPreferences);
                break;
            case ENCHANT_STACK:
                generateEnchantStackPhases(phases, description, context, diff, maxPhases, hasFallbacks, learnedPreferences);
                break;
        }

        if (phases.isEmpty()) return null;

        while (phases.size() > maxPhases) {
            phases.remove(phases.size() - 1);
        }

        return new StrategyPlan(phases, bot.getLocalTickCount(), description.toString());
    }

    // ═════════════════════════════════════════════════════════════
    //  PRESET SELECTION — Weighted scoring based on context
    // ═════════════════════════════════════════════════════════════

    /**
     * Selects the best meta preset for the current game context by scoring each
     * preset against the bot's personality, equipment, game phase, player count,
     * and learned preferences.
     */
    @Nonnull
    private MetaPreset selectPreset(@Nonnull DecisionContext context, @Nonnull DifficultyProfile diff) {
        GamePhaseTracker.GamePhase gamePhase = context.gamePhase;
        if (gamePhase == null) gamePhase = GamePhaseTracker.GamePhase.EARLY;

        double equipScore = context.equipmentScore;
        int alive = context.alivePlayerCount;
        double health = context.healthFraction;
        int chests = context.unlootedChestCount;

        boolean isRusher = bot.getProfile().hasPersonality("RUSHER");
        boolean isDefensive = bot.getProfile().hasPersonality("CAMPER") || bot.getProfile().hasPersonality("STRATEGIST");
        boolean isAggressive = bot.getProfile().hasPersonality("AGGRESSIVE") || bot.getProfile().hasPersonality("BERSERKER");
        boolean isCollector = bot.getProfile().hasPersonality("COLLECTOR");
        boolean isCautious = bot.getProfile().hasPersonality("CAUTIOUS");
        boolean isStrategic = bot.getProfile().hasPersonality("STRATEGIC") || bot.getProfile().hasPersonality("STRATEGIST");
        boolean isSniper = bot.getProfile().hasPersonality("SNIPER");

        Map<MetaPreset, Double> scores = new EnumMap<>(MetaPreset.class);
        for (MetaPreset p : MetaPreset.values()) scores.put(p, 0.0);

        // ── Game Phase Scoring ──
        switch (gamePhase) {
            case EARLY:
                scores.put(MetaPreset.SPEED_RUSH, scores.get(MetaPreset.SPEED_RUSH) + 1.5);
                scores.put(MetaPreset.ISLAND_LOOT_THEN_FIGHT, scores.get(MetaPreset.ISLAND_LOOT_THEN_FIGHT) + 2.0);
                scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) + 1.0);
                scores.put(MetaPreset.ENCHANT_STACK, scores.get(MetaPreset.ENCHANT_STACK) + 1.2);
                scores.put(MetaPreset.DEFENSIVE_FORT, scores.get(MetaPreset.DEFENSIVE_FORT) + 1.0);
                scores.put(MetaPreset.ISLAND_ROTATION, scores.get(MetaPreset.ISLAND_ROTATION) + 0.8);
                break;
            case MID:
                scores.put(MetaPreset.ISLAND_ROTATION, scores.get(MetaPreset.ISLAND_ROTATION) + 1.5);
                scores.put(MetaPreset.THIRD_PARTY, scores.get(MetaPreset.THIRD_PARTY) + 1.3);
                scores.put(MetaPreset.ENCHANT_STACK, scores.get(MetaPreset.ENCHANT_STACK) + 1.0);
                scores.put(MetaPreset.DEFENSIVE_FORT, scores.get(MetaPreset.DEFENSIVE_FORT) + 1.2);
                if (equipScore > 0.5) {
                    scores.put(MetaPreset.SPEED_RUSH, scores.get(MetaPreset.SPEED_RUSH) + 0.5);
                }
                break;
            case LATE:
                scores.put(MetaPreset.THIRD_PARTY, scores.get(MetaPreset.THIRD_PARTY) + (alive == 3 ? 2.0 : 0.5));
                scores.put(MetaPreset.SPEED_RUSH, scores.get(MetaPreset.SPEED_RUSH) + 1.5);
                scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) + 1.5);
                break;
        }

        // ── Personality Scoring ──
        if (isRusher) {
            scores.put(MetaPreset.SPEED_RUSH, scores.get(MetaPreset.SPEED_RUSH) + 2.5);
            scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) + 1.5);
            scores.put(MetaPreset.DEFENSIVE_FORT, scores.get(MetaPreset.DEFENSIVE_FORT) - 1.0);
        }
        if (isAggressive) {
            scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) + 2.0);
            scores.put(MetaPreset.SPEED_RUSH, scores.get(MetaPreset.SPEED_RUSH) + 1.0);
            scores.put(MetaPreset.THIRD_PARTY, scores.get(MetaPreset.THIRD_PARTY) - 1.0);
        }
        if (isDefensive) {
            scores.put(MetaPreset.DEFENSIVE_FORT, scores.get(MetaPreset.DEFENSIVE_FORT) + 2.5);
            scores.put(MetaPreset.THIRD_PARTY, scores.get(MetaPreset.THIRD_PARTY) + 1.0);
            scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) - 1.5);
        }
        if (isCollector) {
            scores.put(MetaPreset.ISLAND_ROTATION, scores.get(MetaPreset.ISLAND_ROTATION) + 2.0);
            scores.put(MetaPreset.ISLAND_LOOT_THEN_FIGHT, scores.get(MetaPreset.ISLAND_LOOT_THEN_FIGHT) + 1.5);
            scores.put(MetaPreset.ENCHANT_STACK, scores.get(MetaPreset.ENCHANT_STACK) + 1.0);
        }
        if (isCautious) {
            scores.put(MetaPreset.DEFENSIVE_FORT, scores.get(MetaPreset.DEFENSIVE_FORT) + 1.5);
            scores.put(MetaPreset.ISLAND_LOOT_THEN_FIGHT, scores.get(MetaPreset.ISLAND_LOOT_THEN_FIGHT) + 1.0);
            scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) - 2.0);
        }
        if (isStrategic) {
            scores.put(MetaPreset.THIRD_PARTY, scores.get(MetaPreset.THIRD_PARTY) + 1.5);
            scores.put(MetaPreset.ENCHANT_STACK, scores.get(MetaPreset.ENCHANT_STACK) + 1.5);
            scores.put(MetaPreset.ISLAND_ROTATION, scores.get(MetaPreset.ISLAND_ROTATION) + 1.0);
        }
        if (isSniper) {
            scores.put(MetaPreset.DEFENSIVE_FORT, scores.get(MetaPreset.DEFENSIVE_FORT) + 1.0);
            scores.put(MetaPreset.THIRD_PARTY, scores.get(MetaPreset.THIRD_PARTY) + 1.0);
        }

        // ── Contextual Scoring ──
        if (equipScore < 0.3 && chests > 0) {
            scores.put(MetaPreset.ISLAND_LOOT_THEN_FIGHT, scores.get(MetaPreset.ISLAND_LOOT_THEN_FIGHT) + 1.5);
            scores.put(MetaPreset.ISLAND_ROTATION, scores.get(MetaPreset.ISLAND_ROTATION) + 1.0);
            scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) - 1.0);
        }
        if (equipScore > 0.7) {
            scores.put(MetaPreset.SPEED_RUSH, scores.get(MetaPreset.SPEED_RUSH) + 1.0);
            scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) + 0.8);
        }
        if (health < 0.4) {
            scores.put(MetaPreset.DEFENSIVE_FORT, scores.get(MetaPreset.DEFENSIVE_FORT) + 2.0);
            scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) - 2.0);
            scores.put(MetaPreset.SPEED_RUSH, scores.get(MetaPreset.SPEED_RUSH) - 1.0);
        }
        if (alive <= 3) {
            scores.put(MetaPreset.THIRD_PARTY, scores.get(MetaPreset.THIRD_PARTY) + 1.5);
        }
        if (alive <= 2) {
            // Final 1v1 — all-in aggro
            scores.put(MetaPreset.SPEED_RUSH, scores.get(MetaPreset.SPEED_RUSH) + 3.0);
            scores.put(MetaPreset.DEFENSIVE_FORT, scores.get(MetaPreset.DEFENSIVE_FORT) - 1.0);
            scores.put(MetaPreset.THIRD_PARTY, scores.get(MetaPreset.THIRD_PARTY) - 3.0);
        }

        // ── Learning influence on preset selection ──
        LearningEngine le = bot.getLearningEngine();
        if (le != null) {
            Map<BotAction, Double> adj = le.getWeightAdjustments();
            Double huntAdj = adj.get(BotAction.HUNT_PLAYER);
            Double lootAdj = adj.get(BotAction.LOOT_OWN_ISLAND);
            Double campAdj = adj.get(BotAction.CAMP_POSITION);
            if (huntAdj != null && huntAdj > 1.2) {
                scores.put(MetaPreset.SPEED_RUSH, scores.get(MetaPreset.SPEED_RUSH) + 0.8);
                scores.put(MetaPreset.EARLY_AGGRO, scores.get(MetaPreset.EARLY_AGGRO) + 0.5);
            }
            if (lootAdj != null && lootAdj > 1.2) {
                scores.put(MetaPreset.ISLAND_ROTATION, scores.get(MetaPreset.ISLAND_ROTATION) + 0.8);
                scores.put(MetaPreset.ENCHANT_STACK, scores.get(MetaPreset.ENCHANT_STACK) + 0.5);
            }
            if (campAdj != null && campAdj > 1.2) {
                scores.put(MetaPreset.DEFENSIVE_FORT, scores.get(MetaPreset.DEFENSIVE_FORT) + 0.8);
                scores.put(MetaPreset.THIRD_PARTY, scores.get(MetaPreset.THIRD_PARTY) + 0.5);
            }
        }

        // ── Decision quality noise — lower quality bots pick worse presets sometimes ──
        double quality = diff.getDecisionQuality();
        double noiseRange = (1.0 - quality) * 1.5;

        // Select the highest-scoring preset
        MetaPreset best = MetaPreset.ISLAND_LOOT_THEN_FIGHT;
        double bestScore = Double.NEGATIVE_INFINITY;
        for (Map.Entry<MetaPreset, Double> entry : scores.entrySet()) {
            double score = entry.getValue() + RandomUtil.nextDouble(-noiseRange, noiseRange);
            if (score > bestScore) {
                bestScore = score;
                best = entry.getKey();
            }
        }

        DebugLogger.log(bot, "StrategyPlanner: Selected preset %s (score=%.2f)", best.name(), bestScore);
        return best;
    }

    // ═════════════════════════════════════════════════════════════
    //  PRESET PHASE GENERATORS
    // ═════════════════════════════════════════════════════════════

    /**
     * SPEED_RUSH: Quick loot → Rush mid → Loot mid → Hunt aggressively.
     * Based on competitive "Scout Rush Mid" meta.
     */
    private void generateSpeedRushPhases(List<StrategicPhase> phases, StringBuilder desc,
                                         DecisionContext ctx, DifficultyProfile diff, int maxPhases,
                                         boolean hasFallbacks, Map<BotAction, Double> learned) {
        // Phase 1: Quick loot (short duration)
        Map<BotAction, Double> quickLoot = new EnumMap<>(BotAction.class);
        quickLoot.put(BotAction.LOOT_OWN_ISLAND, 2.0);
        quickLoot.put(BotAction.ORGANIZE_INVENTORY, 1.2);
        quickLoot.put(BotAction.FIGHT_NEAREST, 0.5);
        applyLearnedInfluence(quickLoot, learned, diff);
        phases.add(new StrategicPhase("Quick Loot", "Grab essentials quickly before rushing",
                quickLoot, c -> c.equipmentScore > 0.3 || c.unlootedChestCount == 0, null, 300));
        desc.append("Quick loot");

        // Phase 2: Rush mid
        if (maxPhases >= 2) {
            Map<BotAction, Double> rushMid = new EnumMap<>(BotAction.class);
            rushMid.put(BotAction.BRIDGE_TO_MID, 2.5);
            rushMid.put(BotAction.LOOT_MID, 2.0);
            rushMid.put(BotAction.FIGHT_NEAREST, 1.3);
            applyLearnedInfluence(rushMid, learned, diff);
            phases.add(new StrategicPhase("Rush Mid", "Bridge to mid for superior loot and position",
                    rushMid, c -> c.onMidIsland,
                    hasFallbacks ? c -> c.healthFraction < 0.2 : null, 600));
            desc.append(" → Rush mid");
        }

        // Phase 3: Hunt
        if (maxPhases >= 3) {
            Map<BotAction, Double> hunt = new EnumMap<>(BotAction.class);
            hunt.put(BotAction.HUNT_PLAYER, 2.0);
            hunt.put(BotAction.FIGHT_NEAREST, 1.8);
            hunt.put(BotAction.FIGHT_WEAKEST, 1.5);
            hunt.put(BotAction.BRIDGE_TO_PLAYER, 1.6);
            hunt.put(BotAction.LOOT_OWN_ISLAND, 0.2);
            applyLearnedInfluence(hunt, learned, diff);
            phases.add(new StrategicPhase("Hunt", "Aggressively seek and eliminate opponents",
                    hunt, c -> c.alivePlayerCount <= 2,
                    hasFallbacks ? c -> c.healthFraction < 0.25 : null, 1200));
            desc.append(" → Hunt");
        }

        appendFinalEngagement(phases, desc, maxPhases, hasFallbacks, learned, diff);
    }

    /**
     * ISLAND_LOOT_THEN_FIGHT: Full loot → Enchant → Engage.
     * The classic "safe" strategy.
     */
    private void generateIslandLootThenFightPhases(List<StrategicPhase> phases, StringBuilder desc,
                                                   DecisionContext ctx, DifficultyProfile diff, int maxPhases,
                                                   boolean hasFallbacks, Map<BotAction, Double> learned) {
        Map<BotAction, Double> fullLoot = new EnumMap<>(BotAction.class);
        fullLoot.put(BotAction.LOOT_OWN_ISLAND, 2.5);
        fullLoot.put(BotAction.ORGANIZE_INVENTORY, 1.5);
        fullLoot.put(BotAction.FIGHT_NEAREST, 0.3);
        fullLoot.put(BotAction.HUNT_PLAYER, 0.2);
        applyLearnedInfluence(fullLoot, learned, diff);
        phases.add(new StrategicPhase("Full Island Loot", "Loot every chest on own island",
                fullLoot, c -> c.equipmentScore > 0.45 || c.unlootedChestCount == 0,
                hasFallbacks ? c -> c.healthFraction < 0.25 && c.visibleEnemyCount > 0 : null, 600));
        desc.append("Full loot");

        if (maxPhases >= 2) {
            Map<BotAction, Double> bridge = new EnumMap<>(BotAction.class);
            bridge.put(BotAction.BRIDGE_TO_MID, 1.8);
            bridge.put(BotAction.ENCHANT, 1.6);
            bridge.put(BotAction.LOOT_MID, 1.4);
            applyLearnedInfluence(bridge, learned, diff);
            phases.add(new StrategicPhase("Bridge & Enchant", "Get to mid, enchant gear",
                    bridge, c -> c.equipmentScore > 0.65,
                    null, 800));
            desc.append(" → Bridge & Enchant");
        }

        if (maxPhases >= 3) {
            Map<BotAction, Double> engage = new EnumMap<>(BotAction.class);
            engage.put(BotAction.HUNT_PLAYER, 1.8);
            engage.put(BotAction.FIGHT_NEAREST, 1.6);
            engage.put(BotAction.BRIDGE_TO_PLAYER, 1.5);
            engage.put(BotAction.FIGHT_WEAKEST, 1.4);
            applyLearnedInfluence(engage, learned, diff);
            phases.add(new StrategicPhase("Engage", "Seek and fight opponents",
                    engage, c -> c.alivePlayerCount <= 2,
                    hasFallbacks ? c -> c.healthFraction < 0.2 : null, 1200));
            desc.append(" → Engage");
        }

        appendFinalEngagement(phases, desc, maxPhases, hasFallbacks, learned, diff);
    }

    /**
     * DEFENSIVE_FORT: Loot → Build defenses → Camp → Counter-punch.
     * Strong against rushers.
     */
    private void generateDefensiveFortPhases(List<StrategicPhase> phases, StringBuilder desc,
                                             DecisionContext ctx, DifficultyProfile diff, int maxPhases,
                                             boolean hasFallbacks, Map<BotAction, Double> learned) {
        Map<BotAction, Double> loot = new EnumMap<>(BotAction.class);
        loot.put(BotAction.LOOT_OWN_ISLAND, 2.5);
        loot.put(BotAction.ORGANIZE_INVENTORY, 1.5);
        loot.put(BotAction.BUILD_FORTIFICATION, 1.0);
        applyLearnedInfluence(loot, learned, diff);
        phases.add(new StrategicPhase("Loot & Prepare", "Gather all resources for defense",
                loot, c -> c.unlootedChestCount == 0 || c.equipmentScore > 0.4, null, 500));
        desc.append("Loot & Prepare");

        if (maxPhases >= 2) {
            Map<BotAction, Double> fort = new EnumMap<>(BotAction.class);
            fort.put(BotAction.BUILD_FORTIFICATION, 2.0);
            fort.put(BotAction.CAMP_POSITION, 1.8);
            fort.put(BotAction.ENCHANT, 1.5);
            fort.put(BotAction.BREAK_ENEMY_BRIDGE, 1.4);
            fort.put(BotAction.HUNT_PLAYER, 0.2);
            applyLearnedInfluence(fort, learned, diff);
            phases.add(new StrategicPhase("Fortify", "Build defenses and hold position",
                    fort, c -> c.timePressure > 0.7 || c.alivePlayerCount <= 2,
                    null, 1500));
            desc.append(" → Fortify");
        }

        if (maxPhases >= 3) {
            Map<BotAction, Double> counter = new EnumMap<>(BotAction.class);
            counter.put(BotAction.FIGHT_NEAREST, 2.0);
            counter.put(BotAction.CAMP_POSITION, 1.3);
            counter.put(BotAction.BREAK_ENEMY_BRIDGE, 1.5);
            counter.put(BotAction.HEAL, 1.2);
            applyLearnedInfluence(counter, learned, diff);
            phases.add(new StrategicPhase("Counter-Punch", "Fight enemies from defensive position",
                    counter, c -> c.alivePlayerCount <= 2,
                    hasFallbacks ? c -> c.healthFraction < 0.15 : null, 1200));
            desc.append(" → Counter-Punch");
        }

        appendFinalEngagement(phases, desc, maxPhases, hasFallbacks, learned, diff);
    }

    /**
     * ISLAND_ROTATION: Loot own island → Bridge to empty islands → Loot them → Fight stacked.
     * Maximizes gear advantage before any engagement.
     */
    private void generateIslandRotationPhases(List<StrategicPhase> phases, StringBuilder desc,
                                              DecisionContext ctx, DifficultyProfile diff, int maxPhases,
                                              boolean hasFallbacks, Map<BotAction, Double> learned) {
        Map<BotAction, Double> lootOwn = new EnumMap<>(BotAction.class);
        lootOwn.put(BotAction.LOOT_OWN_ISLAND, 2.5);
        lootOwn.put(BotAction.ORGANIZE_INVENTORY, 1.3);
        applyLearnedInfluence(lootOwn, learned, diff);
        phases.add(new StrategicPhase("Loot Own Island", "Gather initial gear",
                lootOwn, c -> c.unlootedChestCount == 0 || c.equipmentScore > 0.35, null, 400));
        desc.append("Loot own");

        if (maxPhases >= 2) {
            Map<BotAction, Double> rotate = new EnumMap<>(BotAction.class);
            rotate.put(BotAction.LOOT_OTHER_ISLAND, 2.5);
            rotate.put(BotAction.BRIDGE_TO_MID, 1.5);
            rotate.put(BotAction.LOOT_MID, 1.8);
            rotate.put(BotAction.ENCHANT, 1.3);
            rotate.put(BotAction.FIGHT_NEAREST, 0.4);
            applyLearnedInfluence(rotate, learned, diff);
            phases.add(new StrategicPhase("Island Rotation", "Rotate to other islands for more loot",
                    rotate, c -> c.equipmentScore > 0.7,
                    hasFallbacks ? c -> c.healthFraction < 0.25 && c.visibleEnemyCount > 0 : null, 1000));
            desc.append(" → Rotate islands");
        }

        if (maxPhases >= 3) {
            Map<BotAction, Double> hunt = new EnumMap<>(BotAction.class);
            hunt.put(BotAction.HUNT_PLAYER, 2.0);
            hunt.put(BotAction.FIGHT_WEAKEST, 1.8);
            hunt.put(BotAction.FIGHT_NEAREST, 1.5);
            hunt.put(BotAction.BRIDGE_TO_PLAYER, 1.6);
            applyLearnedInfluence(hunt, learned, diff);
            phases.add(new StrategicPhase("Hunt Stacked", "Engage with gear advantage",
                    hunt, c -> c.alivePlayerCount <= 2,
                    hasFallbacks ? c -> c.healthFraction < 0.2 : null, 1200));
            desc.append(" → Hunt stacked");
        }

        appendFinalEngagement(phases, desc, maxPhases, hasFallbacks, learned, diff);
    }

    /**
     * THIRD_PARTY: Loot → Camp & observe → Clean up weakened survivors.
     * Best when 3+ players remain.
     */
    private void generateThirdPartyPhases(List<StrategicPhase> phases, StringBuilder desc,
                                          DecisionContext ctx, DifficultyProfile diff, int maxPhases,
                                          boolean hasFallbacks, Map<BotAction, Double> learned) {
        Map<BotAction, Double> loot = new EnumMap<>(BotAction.class);
        loot.put(BotAction.LOOT_OWN_ISLAND, 2.0);
        loot.put(BotAction.ENCHANT, 1.5);
        loot.put(BotAction.ORGANIZE_INVENTORY, 1.3);
        applyLearnedInfluence(loot, learned, diff);
        phases.add(new StrategicPhase("Prepare Quietly", "Gear up while others fight",
                loot, c -> c.equipmentScore > 0.5 || c.unlootedChestCount == 0, null, 600));
        desc.append("Prepare quietly");

        if (maxPhases >= 2) {
            Map<BotAction, Double> wait = new EnumMap<>(BotAction.class);
            wait.put(BotAction.CAMP_POSITION, 2.0);
            wait.put(BotAction.HEAL, 1.5);
            wait.put(BotAction.EAT_FOOD, 1.4);
            wait.put(BotAction.BREAK_ENEMY_BRIDGE, 1.2);
            wait.put(BotAction.FIGHT_NEAREST, 0.4);
            wait.put(BotAction.HUNT_PLAYER, 0.3);
            applyLearnedInfluence(wait, learned, diff);
            phases.add(new StrategicPhase("Observe & Wait", "Let others fight each other",
                    wait, c -> c.alivePlayerCount <= 2 || c.timePressure > 0.85,
                    null, 1500));
            desc.append(" → Observe & Wait");
        }

        if (maxPhases >= 3) {
            Map<BotAction, Double> cleanup = new EnumMap<>(BotAction.class);
            cleanup.put(BotAction.HUNT_PLAYER, 2.5);
            cleanup.put(BotAction.FIGHT_WEAKEST, 2.0);
            cleanup.put(BotAction.FIGHT_NEAREST, 1.8);
            cleanup.put(BotAction.USE_ENDER_PEARL, 1.5);
            cleanup.put(BotAction.BRIDGE_TO_PLAYER, 1.6);
            applyLearnedInfluence(cleanup, learned, diff);
            phases.add(new StrategicPhase("Clean Up", "Eliminate weakened survivors",
                    cleanup, c -> c.alivePlayerCount <= 1,
                    hasFallbacks ? c -> c.healthFraction < 0.15 : null, 1000));
            desc.append(" → Clean up");
        }

        appendFinalEngagement(phases, desc, maxPhases, hasFallbacks, learned, diff);
    }

    /**
     * EARLY_AGGRO: Minimal loot → Rush nearest player → Snowball kills.
     * High risk, high reward. Strong with good PvP mechanics.
     */
    private void generateEarlyAggroPhases(List<StrategicPhase> phases, StringBuilder desc,
                                          DecisionContext ctx, DifficultyProfile diff, int maxPhases,
                                          boolean hasFallbacks, Map<BotAction, Double> learned) {
        Map<BotAction, Double> minLoot = new EnumMap<>(BotAction.class);
        minLoot.put(BotAction.LOOT_OWN_ISLAND, 1.5);
        minLoot.put(BotAction.ORGANIZE_INVENTORY, 1.0);
        applyLearnedInfluence(minLoot, learned, diff);
        // Very short loot phase — grab sword and go
        phases.add(new StrategicPhase("Grab & Go", "Grab a weapon and basic gear immediately",
                minLoot, c -> c.equipmentScore > 0.15 || c.unlootedChestCount <= 1, null, 200));
        desc.append("Grab & Go");

        if (maxPhases >= 2) {
            Map<BotAction, Double> rush = new EnumMap<>(BotAction.class);
            rush.put(BotAction.BRIDGE_TO_PLAYER, 2.5);
            rush.put(BotAction.FIGHT_NEAREST, 2.0);
            rush.put(BotAction.HUNT_PLAYER, 2.0);
            rush.put(BotAction.FIGHT_WEAKEST, 1.5);
            rush.put(BotAction.LOOT_OWN_ISLAND, 0.1);
            rush.put(BotAction.ENCHANT, 0.1);
            applyLearnedInfluence(rush, learned, diff);
            phases.add(new StrategicPhase("Rush Player", "Rush nearest player's island and fight",
                    rush, c -> c.alivePlayerCount <= 2,
                    hasFallbacks ? c -> c.healthFraction < 0.2 : null, 1000));
            desc.append(" → Rush player");
        }

        if (maxPhases >= 3) {
            // Loot their drops and continue
            Map<BotAction, Double> lootAndContinue = new EnumMap<>(BotAction.class);
            lootAndContinue.put(BotAction.LOOT_OTHER_ISLAND, 1.8);
            lootAndContinue.put(BotAction.HUNT_PLAYER, 1.5);
            lootAndContinue.put(BotAction.FIGHT_NEAREST, 1.5);
            lootAndContinue.put(BotAction.HEAL, 1.3);
            applyLearnedInfluence(lootAndContinue, learned, diff);
            phases.add(new StrategicPhase("Loot Kills & Continue", "Collect drops and hunt next target",
                    lootAndContinue, c -> c.alivePlayerCount <= 2,
                    null, 800));
            desc.append(" → Loot & Continue");
        }

        appendFinalEngagement(phases, desc, maxPhases, hasFallbacks, learned, diff);
    }

    /**
     * ENCHANT_STACK: Loot → Rush mid for enchanting table → Enchant everything → Dominate.
     * The "Blacksmith" meta — maximum gear quality.
     */
    private void generateEnchantStackPhases(List<StrategicPhase> phases, StringBuilder desc,
                                            DecisionContext ctx, DifficultyProfile diff, int maxPhases,
                                            boolean hasFallbacks, Map<BotAction, Double> learned) {
        Map<BotAction, Double> loot = new EnumMap<>(BotAction.class);
        loot.put(BotAction.LOOT_OWN_ISLAND, 2.5);
        loot.put(BotAction.ORGANIZE_INVENTORY, 1.3);
        applyLearnedInfluence(loot, learned, diff);
        phases.add(new StrategicPhase("Initial Loot", "Get basic gear and XP bottles",
                loot, c -> c.unlootedChestCount == 0 || c.equipmentScore > 0.35, null, 500));
        desc.append("Initial loot");

        if (maxPhases >= 2) {
            Map<BotAction, Double> midEnchant = new EnumMap<>(BotAction.class);
            midEnchant.put(BotAction.BRIDGE_TO_MID, 2.0);
            midEnchant.put(BotAction.ENCHANT, 2.5);
            midEnchant.put(BotAction.LOOT_MID, 1.5);
            midEnchant.put(BotAction.ORGANIZE_INVENTORY, 1.3);
            midEnchant.put(BotAction.FIGHT_NEAREST, 0.5);
            applyLearnedInfluence(midEnchant, learned, diff);
            phases.add(new StrategicPhase("Mid Enchant", "Rush mid for enchanting table, enchant all gear",
                    midEnchant, c -> c.equipmentScore > 0.8,
                    hasFallbacks ? c -> c.healthFraction < 0.2 && c.visibleEnemyCount > 0 : null, 800));
            desc.append(" → Mid enchant");
        }

        if (maxPhases >= 3) {
            Map<BotAction, Double> dominate = new EnumMap<>(BotAction.class);
            dominate.put(BotAction.HUNT_PLAYER, 2.0);
            dominate.put(BotAction.FIGHT_NEAREST, 1.8);
            dominate.put(BotAction.FIGHT_WEAKEST, 1.5);
            dominate.put(BotAction.BRIDGE_TO_PLAYER, 1.6);
            dominate.put(BotAction.USE_ENDER_PEARL, 1.3);
            applyLearnedInfluence(dominate, learned, diff);
            phases.add(new StrategicPhase("Dominate", "Hunt with superior enchanted gear",
                    dominate, c -> c.alivePlayerCount <= 2,
                    hasFallbacks ? c -> c.healthFraction < 0.2 : null, 1200));
            desc.append(" → Dominate");
        }

        appendFinalEngagement(phases, desc, maxPhases, hasFallbacks, learned, diff);
    }

    /**
     * Appends a "Final Engagement" phase for plans with enough complexity slots.
     * This is the endgame all-in phase present in most presets.
     */
    private void appendFinalEngagement(List<StrategicPhase> phases, StringBuilder desc,
                                       int maxPhases, boolean hasFallbacks,
                                       Map<BotAction, Double> learned, DifficultyProfile diff) {
        if (phases.size() >= maxPhases) return;
        if (maxPhases >= 4) {
            Map<BotAction, Double> finalPhase = new EnumMap<>(BotAction.class);
            finalPhase.put(BotAction.FIGHT_NEAREST, 2.0);
            finalPhase.put(BotAction.FIGHT_WEAKEST, 1.8);
            finalPhase.put(BotAction.HUNT_PLAYER, 2.0);
            finalPhase.put(BotAction.BRIDGE_TO_PLAYER, 1.8);
            finalPhase.put(BotAction.USE_ENDER_PEARL, 1.5);
            finalPhase.put(BotAction.HEAL, 1.3);
            finalPhase.put(BotAction.CAMP_POSITION, 0.2);
            finalPhase.put(BotAction.LOOT_OWN_ISLAND, 0.1);
            applyLearnedInfluence(finalPhase, learned, diff);
            phases.add(new StrategicPhase("Final Engagement", "Eliminate all remaining opponents",
                    finalPhase, null,
                    hasFallbacks ? c -> c.healthFraction < 0.1 : null, 2400));
            if (desc.length() > 0) desc.append(" → ");
            desc.append("Final engagement");
        }
    }

    // ─── Learning Data Consultation ─────────────────────────────

    @Nonnull
    private Map<BotAction, Double> getLearnedPreferences(@Nonnull DecisionContext context,
                                                         @Nonnull DifficultyProfile diff) {
        Map<BotAction, Double> prefs = new EnumMap<>(BotAction.class);
        double influence = diff.getPlanLearningInfluence();
        if (influence <= 0.0) return prefs;

        LearningEngine le = bot.getLearningEngine();
        if (le == null) return prefs;

        Map<BotAction, Double> adjustments = le.getWeightAdjustments();
        if (adjustments.isEmpty()) return prefs;

        for (Map.Entry<BotAction, Double> entry : adjustments.entrySet()) {
            double rawMult = entry.getValue();
            double blended = 1.0 + influence * (rawMult - 1.0);
            prefs.put(entry.getKey(), MathUtil.clamp(blended, 0.5, 2.0));
        }

        return prefs;
    }

    private void applyLearnedInfluence(@Nonnull Map<BotAction, Double> multipliers,
                                       @Nonnull Map<BotAction, Double> learnedPreferences,
                                       @Nonnull DifficultyProfile diff) {
        if (learnedPreferences.isEmpty()) return;
        for (Map.Entry<BotAction, Double> entry : learnedPreferences.entrySet()) {
            BotAction action = entry.getKey();
            double learnedMult = entry.getValue();
            if (multipliers.containsKey(action)) {
                double current = multipliers.get(action);
                multipliers.put(action, current * learnedMult);
            }
        }
    }

    // ─── Significant Events ─────────────────────────────────────

    public void onSignificantEvent(@Nonnull String eventType) {
        if (activePlan == null) return;
        switch (eventType) {
            case "kill":
                activePlan.setConfidence(Math.min(1.0, activePlan.getConfidence() + 0.1));
                break;
            case "death":
            case "player_death":
                activePlan.setConfidence(activePlan.getConfidence() * 0.6);
                break;
            case "phase_change":
                activePlan.setConfidence(activePlan.getConfidence() * 0.3);
                break;
            case "health_critical":
                activePlan.setConfidence(0.0);
                break;
            default:
                activePlan.setConfidence(activePlan.getConfidence() * 0.9);
                break;
        }

        // On significant events, consider re-consulting LLM
        DifficultyProfile diff = bot.getDifficultyProfile();
        if (diff != null && diff.getPlanLLMConsultChance() > 0.3
                && ("phase_change".equals(eventType) || "health_critical".equals(eventType))) {
            requestLLMAdvice();
        }
    }

    public void onLLMAdviceReceived(@Nullable String adviceDescription,
                                    @Nonnull Map<BotAction, Double> adviceMultipliers,
                                    double confidence) {
        this.lastLLMAdvice = adviceDescription;
        this.lastLLMConfidence = confidence;
        this.llmMultipliers.clear();
        this.llmMultipliers.putAll(adviceMultipliers);

        if (activePlan != null && !adviceMultipliers.isEmpty()) {
            activePlan.setConfidence(Math.min(1.0, activePlan.getConfidence() + 0.15 * confidence));
        }

        DebugLogger.log(bot, "LLM advice received: %s (multipliers=%d, confidence=%.3f)",
                adviceDescription != null ? adviceDescription : "none",
                adviceMultipliers.size(), confidence);
    }

    // ─── Queries ────────────────────────────────────────────────

    @Nonnull
    public Map<BotAction, Double> getActiveMultipliers() {
        Map<BotAction, Double> result = new EnumMap<>(BotAction.class);

        if (activePlan != null) {
            result.putAll(activePlan.getActiveMultipliers());
        }

        if (!llmMultipliers.isEmpty()) {
            double conf = lastLLMConfidence;
            for (Map.Entry<BotAction, Double> entry : llmMultipliers.entrySet()) {
                BotAction action = entry.getKey();
                double llmMult = entry.getValue();
                if (result.containsKey(action)) {
                    double planMult = result.get(action);
                    result.put(action, planMult * (1.0 - conf * 0.5) + llmMult * conf * 0.5);
                } else {
                    result.put(action, 1.0 + conf * (llmMult - 1.0));
                }
            }
        }

        return result;
    }

    @Nullable
    public StrategyPlan getActivePlan() {
        return activePlan;
    }

    public boolean hasActivePlan() {
        return activePlan != null;
    }

    @Nullable
    public String getLastLLMAdvice() {
        return lastLLMAdvice;
    }
}
